src/testapp/events/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from testapp import db, bcrypt


events = Blueprint('events', __name__)


@events.route("/events/concerts")
def concerts():
    return render_template('events/concerts.html', title='Concerts')

@events.route("/events/concert1")
def concert1():
    return render_template('concerts/concert1.html', title='Concert1')

@events.route("/events/concert2")
def concert2():
    return render_template('concerts/concert2.html', title='Concert1')

@events.route("/events/concert3")
def concert3():
    return render_template('concerts/concert3.html', title='Concert1')


@events.route("/events/fine_arts")
def fine_arts():
    return render_template('events/fine_arts.html', title='Fine Arts')

@events.route("/events/fine_arts1")
def fine_arts1():
    return render_template('fine_arts/fine_arts1.html', title='Fine Arts1')

@events.route("/events/fine_arts2")
def fine_arts2():
    return render_template('fine_arts/fine_arts2.html', title='Fine Arts2')

@events.route("/events/fine_arts3")
def fine_arts3():
    return render_template('fine_arts/fine_arts3.html', title='Fine Arts3')



@events.route("/events/gaming")
def gaming():
    return render_template('events/gaming.html', title='Gaming')

@events.route("/events/gaming1")
def gaming1():
    return render_template('gaming/gaming1.html', title='Gaming1')

@events.route("/events/gaming2")
def gaming2():
    return render_template('gaming/gaming2.html', title='Gaming2')

@events.route("/events/gaming3")
def gaming3():
    return render_template('gaming/gaming3.html', title='Gaming3')



@events.route("/events/informals")
def informals():
    return render_template('events/informals.html', title='Informals')

@events.route("/events/informals1")
def informals1():
    return render_template('informals/informals1.html', title='Informals1')

@events.route("/events/informals2")
def informals2():
    return render_template('informals/informals2.html', title='Informals-2')

@events.route("/events/informals3")
def informals3():
    return render_template('informals/informals3.html', title='Informals-3')



@events.route("/events/literary_arts")
def literary_arts():
    return render_template('events/literary_arts.html', title='Literary Arts')

@events.route("/events/literary_arts1")
def literary_arts1():
    return render_template('literary_arts/literary_arts1.html', title='Literary Arts-1')

@events.route("/events/literary_arts2")
def literary_arts2():
    return render_template('literary_arts/literary_arts2.html', title='Literary Arts-2')

@events.route("/events/literary_arts3")
def literary_arts3():
    return render_template('literary_arts/literary_arts3.html', title='Literary Arts-3')


@events.route("/events/management")
def management():
    return render_template('events/management.html', title='Management')

@events.route("/events/management1")
def management1():
    return render_template('management/management1.html', title='Management-1')

@events.route("/events/management2")
def management2():
    return render_template('management/management2.html', title='Management-2')

@events.route("/events/management3")
def management3():
    return render_template('management/management3.html', title='Management-3')



@events.route("/events/performing_arts")
def performing_arts():
    return render_template('events/performing_arts.html', title='Performing Arts')

@events.route("/events/performing_arts1")
def performing_arts1():
    return render_template('performing_arts/performing_arts1.html', title='Performing Arts-1')

@events.route("/events/performing_arts2")
def performing_arts2():
    return render_template('performing_arts/performing_arts2.html', title='Performing Arts-2')

@events.route("/events/performing_arts3")
def performing_arts3():
    return render_template('performing_arts/performing_arts3.html', title='Performing Arts-3')



@events.route("/events/sports")
def sports():
    return render_template('events/sports.html', title='Sports')

@events.route("/events/sports1")
def sports1():
    return render_template('sports/sports1.html', title='Sports-1')

@events.route("/events/sports2")
def sports2():
    return render_template('sports/sports2.html', title='Sports-2')

@events.route("/events/sports3")
def sports3():
    return render_template('sports/sports3.html', title='Sports-3')



@events.route("/events/tech_events")
def tech_events():
    return render_template('events/tech_events.html', title='Technical Events')

@events.route("/events/tech_events1")
def tech_events1():
    return render_template('tech_events/tech_events1.html', title='Technical Events-1')

@events.route("/events/tech_events2")
def tech_events2():
    return render_template('tech_events/tech_events2.html', title='Technical Events-2')

@events.route("/events/tech_events3")
def tech_events3():
    return render_template('tech_events/tech_events3.html', title='Technical Events-3')



@events.route("/events/tech_workshops")
def tech_workshops():
    return render_template('events/tech_workshops.html', title='Technical Workshops')

@events.route("/events/tech_workshops1")
def tech_workshops1():
    return render_template('tech_workshops/tech_workshops1.html', title='Technical Workshops-1')

@events.route("/events/tech_workshops2")
def tech_workshops2():
    return render_template('tech_workshops/tech_workshops2.html', title='Technical Workshops-2')

@events.route("/events/tech_workshops3")
def tech_workshops3():
    return render_template('tech_workshops/tech_workshops3.html', title='Technical Workshops-3')



@events.route("/events/workshops")
def workshops():
    return render_template('events/workshops.html', title='Workshops')

@events.route("/events/workshops1")
def workshops1():
    return render_template('workshops/workshops1.html', title='Workshops-1')

@events.route("/events/workshops2")
def workshops2():
    return render_template('workshops/workshops2.html', title='Workshops-2')

@events.route("/events/workshops3")
def workshops3():
    return render_template('workshops/workshops3.html', title='Workshops-3')

src/testapp/templates/events/concerts.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/concerts.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/concerts.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/concerts.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.concert1') }}">
        <div class="xop-info">
          <h3>Concert-1</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.concert2') }}">
        <div class="xop-info">
          <h3>Concert-2</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.concert3') }}">
        <div class="xop-info">
          <h3>Concert-3</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}

src/testapp/templates/events/fine_arts.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/fine_arts.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/fine_arts.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/fine_arts.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.fine_arts1') }}">
        <div class="xop-info">
          <h3>Fine Arts-1</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.fine_arts2') }}">
        <div class="xop-info">
          <h3>Fine Arts-2</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.fine_arts3') }}">
        <div class="xop-info">
          <h3>Fine Arts-3</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}

src/testapp/templates/events/gaming.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/gaming.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/gaming.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/gaming.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.gaming1') }}">
        <div class="xop-info">
          <h3>Gaming-1</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.gaming2') }}">
        <div class="xop-info">
          <h3>Gaming-2</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.gaming3') }}">
        <div class="xop-info">
          <h3>Gaming-3</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}

src/testapp/templates/events/informals.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/informals.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/informals.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/informals.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.informals1') }}">
        <div class="xop-info">
          <h3>Informals-1</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.informals2') }}">
        <div class="xop-info">
          <h3>Informals-2</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.informals3') }}">
        <div class="xop-info">
          <h3>Informals-3</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}

src/testapp/templates/events/literary_arts.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/literary_arts.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/literary_arts.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/literary_arts.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.literary_arts1') }}">
        <div class="xop-info">
          <h3>Literary Arts-1</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.literary_arts2') }}">
        <div class="xop-info">
          <h3>Literary Arts-2</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.literary_arts3') }}">
        <div class="xop-info">
          <h3>Literary Arts-3</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}

src/testapp/templates/events/management.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/management.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/management.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/management.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.management1') }}">
        <div class="xop-info">
          <h3>Management-1</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.management2') }}">
        <div class="xop-info">
          <h3>Management-2</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.management3') }}">
        <div class="xop-info">
          <h3>Management-3</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}

src/testapp/templates/events/performing_arts.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/performing_arts.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/performing_arts.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/performing_arts.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.performing_arts1') }}">
        <div class="xop-info">
          <h3>Performing Arts-1</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.performing_arts2') }}">
        <div class="xop-info">
          <h3>Performing Arts-2</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.performing_arts3') }}">
        <div class="xop-info">
          <h3>Performing Arts-3</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}