src/testapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

src/testapp/events/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from testapp import db, bcrypt


events = Blueprint('events', __name__)


@events.route("/events/concerts")
def concerts():
    return render_template('events/concerts.html', title='Concerts')

@events.route("/events/concert1")
def concert1():
    return render_template('concerts/concert1.html', title='Concert1')

@events.route("/events/concert2")
def concert2():
    return render_template('concerts/concert2.html', title='Concert1')

@events.route("/events/concert3")
def concert3():
    return render_template('concerts/concert3.html', title='Concert1')


@events.route("/events/fine_arts")
def fine_arts():
    return render_template('events/fine_arts.html', title='Fine Arts')

@events.route("/events/fine_arts1")
def fine_arts1():
    return render_template('fine_arts/fine_arts1.html', title='Fine Arts1')

@events.route("/events/fine_arts2")
def fine_arts2():
    return render_template('fine_arts/fine_arts2.html', title='Fine Arts2')

@events.route("/events/fine_arts3")
def fine_arts3():
    return render_template('fine_arts/fine_arts3.html', title='Fine Arts3')



@events.route("/events/gaming")
def gaming():
    return render_template('events/gaming.html', title='Gaming')

@events.route("/events/gaming1")
def gaming1():
    return render_template('gaming/gaming1.html', title='Gaming1')

@events.route("/events/gaming2")
def gaming2():
    return render_template('gaming/gaming2.html', title='Gaming2')

@events.route("/events/gaming3")
def gaming3():
    return render_template('gaming/gaming3.html', title='Gaming3')



@events.route("/events/informals")
def informals():
    return render_template('events/informals.html', title='Informals')

@events.route("/events/informals1")
def informals1():
    return render_template('informals/informals1.html', title='Informals1')

@events.route("/events/informals2")
def informals2():
    return render_template('informals/informals2.html', title='Informals-2')

@events.route("/events/informals3")
def informals3():
    return render_template('informals/informals3.html', title='Informals-3')



@events.route("/events/literary_arts")
def literary_arts():
    return render_template('events/literary_arts.html', title='Literary Arts')

@events.route("/events/literary_arts1")
def literary_arts1():
    return render_template('literary_arts/literary_arts1.html', title='Literary Arts-1')

@events.route("/events/literary_arts2")
def literary_arts2():
    return render_template('literary_arts/literary_arts2.html', title='Literary Arts-2')

@events.route("/events/literary_arts3")
def literary_arts3():
    return render_template('literary_arts/literary_arts3.html', title='Literary Arts-3')


@events.route("/events/management")
def management():
    return render_template('events/management.html', title='Management')

@events.route("/events/management1")
def management1():
    return render_template('management/management1.html', title='Management-1')

@events.route("/events/management2")
def management2():
    return render_template('management/management2.html', title='Management-2')

@events.route("/events/management3")
def management3():
    return render_template('management/management3.html', title='Management-3')



@events.route("/events/performing_arts")
def performing_arts():
    return render_template('events/performing_arts.html', title='Performing Arts')

@events.route("/events/performing_arts1")
def performing_arts1():
    return render_template('performing_arts/performing_arts1.html', title='Performing Arts-1')

@events.route("/events/performing_arts2")
def performing_arts2():
    return render_template('performing_arts/performing_arts2.html', title='Performing Arts-2')

@events.route("/events/performing_arts3")
def performing_arts3():
    return render_template('performing_arts/performing_arts3.html', title='Performing Arts-3')



@events.route("/events/sports")
def sports():
    return render_template('events/sports.html', title='Sports')

@events.route("/events/sports1")
def sports1():
    return render_template('sports/sports1.html', title='Sports-1')

@events.route("/events/sports2")
def sports2():
    return render_template('sports/sports2.html', title='Sports-2')

@events.route("/events/sports3")
def sports3():
    return render_template('sports/sports3.html', title='Sports-3')



@events.route("/events/tech_events")
def tech_events():
    return render_template('events/tech_events.html', title='Technical Events')

@events.route("/events/tech_events1")
def tech_events1():
    return render_template('tech_events/tech_events1.html', title='Technical Events-1')

@events.route("/events/tech_events2")
def tech_events2():
    return render_template('tech_events/tech_events2.html', title='Technical Events-2')

@events.route("/events/tech_events3")
def tech_events3():
    return render_template('tech_events/tech_events3.html', title='Technical Events-3')



@events.route("/events/tech_workshops")
def tech_workshops():
    return render_template('events/tech_workshops.html', title='Technical Workshops')

@events.route("/events/tech_workshops1")
def tech_workshops1():
    return render_template('tech_workshops/tech_workshops1.html', title='Technical Workshops-1')

@events.route("/events/tech_workshops2")
def tech_workshops2():
    return render_template('tech_workshops/tech_workshops2.html', title='Technical Workshops-2')

@events.route("/events/tech_workshops3")
def tech_workshops3():
    return render_template('tech_workshops/tech_workshops3.html', title='Technical Workshops-3')



@events.route("/events/workshops")
def workshops():
    return render_template('events/workshops.html', title='Workshops')

@events.route("/events/workshops1")
def workshops1():
    return render_template('workshops/workshops1.html', title='Workshops-1')

@events.route("/events/workshops2")
def workshops2():
    return render_template('workshops/workshops2.html', title='Workshops-2')

@events.route("/events/workshops3")
def workshops3():
    return render_template('workshops/workshops3.html', title='Workshops-3')

src/testapp/main/routes.py
from flask import render_template, request, Blueprint
from testapp.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/events")
def events():
    return render_template('events.html', title='Events')

@main.route("/offers")
def offers():
    return render_template('offers.html', title='Offers')

@main.route("/calender")
def calender():
    return render_template('calender.html', title='Calender')

@main.route("/wishlist")
def wishlist():
    return render_template('wishlist.html', title='Your Cart')

src/testapp/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from testapp import db
from testapp.models import Post
from testapp.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.username == 'admin':
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            db.session.commit()
            flash('Your post has been updated!', 'success')
            return redirect(url_for('posts.post', post_id=post.id))
        elif request.method == 'GET':
            form.title.data = post.title
            form.content.data = post.content
        return render_template('create_post.html', title='Update Post',
                               form=form, legend='Update Post')
    elif post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.username == 'admin':
        db.session.delete(post)
        db.session.commit()
        flash('The post has been deleted!', 'success')
        return redirect(url_for('main.home'))
    elif post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

src/testapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from testapp import db, bcrypt
from testapp.models import User, Post
from testapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPassswordForm
from testapp.users.utils import save_picture, send_reset_email


users = Blueprint('users',__name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Request', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPassswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Request', form=form)


@users.route("/wishlist")
@login_required
def wishlist():
    return render_template('wishlist.html')

src/testapp/templates/about.html
{% extends "layout.html" %}
{% block content %}
  <h1>About Page</h1>
  <div>
      <img src="{{ url_for('static', filename='Alegria2.jpg') }}">
  </div>
{% endblock content %}

src/testapp/templates/calender.html
{% extends "layout.html" %}
{% block content %}
  <h1>Event Calender</h1>
{% endblock content %}

src/testapp/templates/event_layout.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <div class="media-body">
            {% block event %}{% endblock %}
            <button type="button" class="btn btn-outline-info">Add To Wishlist</button>
        </div>
    </div>
</div>
{% endblock content %}

src/testapp/templates/events.html
{% extends "layout2.html" %}
{% block content %}
<head>
<style>
.xop-grid li {
    	width: 328px;
    	height: 328px;
    	display: inline-block;
    	margin: 20px;
    }

.xop-box {
	width: 100%;
	height: 100%;
	position: relative;
	cursor: pointer;
    border-radius: 10px;
    -webkit-transition: 0.3s ease-in-out,
    -webkit-transform 0.3s ease-in-out;
	-moz-transition:  0.3s ease-in-out,
    -moz-transform 0.3s ease-in-out;
    transition: all 0.3s ease-in-out,
    transform 0.3s ease-in-out, ;
}

.xop-box:hover {
	transform: scale(1.05);
}

.xop-img-1 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
	url(../static/events_img/concerts.jpg);
}

.xop-img-2 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/fine_arts.jpg);
}

.xop-img-3 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/gaming.jpg);
}

.xop-img-4 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/informals.jpg);
}

.xop-img-5 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/literary_arts.jpg);
}

.xop-img-6 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/management.jpg);
}

.xop-img-7 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/performing_arts.jpg);
}

.xop-img-8 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/sports.jpg);
}

.xop-img-9 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/tech_events.jpg);
}

.xop-img-10 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/tech_workshops.jpg);
}

.xop-img-11 {
	background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10)), /* bottom, image */
    url(../static/events_img/workshops.jpg);
}

.xop-info {
	position: absolute;
	width: inherit;
	height: inherit;
}

.xop-info h3 {
	font-family: 'Pacifico', cursive;
	font-weight: 400;
	color: #fff;
	font-size: 42px;
	margin: 0 30px;
	padding: 100px 0 0 0;
	line-height: 1.5;
}

.xop-info p {
	font-family: 'Source Sans Pro', sans-serif;
	color: #fff;
	padding: 4px 5px;
	margin: 0 30px;
	font-size: 14px;
	line-height: 2;
}

h1{
    text-align: center
}
</style>
</head>
<div>
    <h1>Events Categories</h1>
</div>
<div>
    <h1>List</h1>
</div>
<div class="xop-section">
  <ul class="xop-grid">
    <li>
      <div class="xop-box xop-img-1">
        <a href="{{ url_for('events.concerts') }}">
        <div class="xop-info">
          <h3>Concerts</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-2">
          <a href="{{ url_for('events.fine_arts') }}">
        <div class="xop-info">
          <h3>Fine Arts</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-3">
        <a href="{{ url_for('events.gaming') }}">
        <div class="xop-info">
          <h3>Gaming</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-4">
        <a href="{{ url_for('events.informals') }}">
        <div class="xop-info">
          <h3>Informals</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-5">
        <a href="{{ url_for('events.literary_arts') }}">
        <div class="xop-info">
          <h3>Literary Arts</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-6">
        <a href="{{ url_for('events.management') }}">
        <div class="xop-info">
          <h3>Management</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-7">
        <a href="{{ url_for('events.performing_arts') }}">
        <div class="xop-info">
          <h3>Performing Arts</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-8">
        <a href="{{ url_for('events.sports') }}">
        <div class="xop-info">
          <h3>Sports</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-9">
        <a href="{{ url_for('events.tech_events') }}">
        <div class="xop-info">
          <h3>Technical Events</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-10">
        <a href="{{ url_for('events.tech_workshops') }}">
        <div class="xop-info">
          <h3>Technical Workshops</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
    <li>
      <div class="xop-box xop-img-11">
        <a href="{{ url_for('events.workshops') }}">
        <div class="xop-info">
          <h3>Workshops</h3>
          <p>Nulla commodo iaculis vulputate.</p>
        </div></a>
      </div>
    </li>
  </ul>
</div>
{% endblock content %}

src/testapp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Alegria - {{ title }}</title>
    {% else %}
        <title>Alegria</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Alegria</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.events') }}">Events</a>
              <a class="nav-item nav-link" href="{{ url_for('main.offers') }}">Offers!</a>
              <a class="nav-item nav-link" href="{{ url_for('main.calender') }}">Calender</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                {% if current_user.username == 'admin' %}
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.wishlist') }}">Wishlist</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.wishlist') }}">Wishlist</a>
                {% endif %}
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <!--
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>-->
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

src/testapp/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
        {% if post.author == current_user %}
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
        {% elif current_user.username == 'admin' %}
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger"type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

src/testapp/templates/wishlist.html
{% extends "layout.html" %}
{% block content %}
  <h1>Your Wishlist</h1>
{% endblock content %}